import { currentYear } from '@/app/common/constants'

export type UserType = {
  name: string
  email: string
  image: string
  id: string
  role: string
  last_active: string
  status: string
}

export const UserData: UserType[] = [
  {
    name: 'Francisco Ventura',
    email: 'ingfranciscoventurac@gmail.com',
    image: 'assets/images/users/avatar-1.jpg',
    id: '#9958',
    role: 'Administrador',
    last_active: 'Today, 02:30pm',
    status: 'Activo',
  },
  {
    name: 'Ben',
    email: 'exemple@gmail.com',
    image: 'assets/images/users/avatar-1.jpg',
    id: '#3625',
    role: 'Administrador',
    last_active: 'Yesterday, 10:15pm',
    status: 'Activo',
  },
  {
    name: 'Mickey',
    email: 'josealbertopersonal@gmail.com',
    image: 'assets/images/users/avatar-2.jpg',
    id: '#9514',
    role: 'SubAgente',
    last_active: 'Today, 02:30pm',
    status: 'Activo',
  },
  {
    name: 'Francisco Ventura',
    email: 'ingfranciscoventurac@gmail.com',
    image: 'assets/images/users/avatar-1.jpg',
    id: '#9958',
    role: 'Administrador',
    last_active: 'Today, 02:30pm',
    status: 'Activo',
  },
  {
    name: 'Ben',
    email: 'exemple@gmail.com',
    image: 'assets/images/users/avatar-1.jpg',
    id: '#3625',
    role: 'Administrador',
    last_active: 'Yesterday, 10:15pm',
    status: 'Activo',
  },
  {
    name: 'Mickey',
    email: 'josealbertopersonal@gmail.com',
    image: 'assets/images/users/avatar-2.jpg',
    id: '#9514',
    role: 'SubAgente',
    last_active: 'Today, 02:30pm',
    status: 'Activo',
  },
  {
    name: 'Francisco Ventura',
    email: 'ingfranciscoventurac@gmail.com',
    image: 'assets/images/users/avatar-1.jpg',
    id: '#9958',
    role: 'Administrador',
    last_active: 'Today, 02:30pm',
    status: 'Activo',
  },
  {
    name: 'Ben',
    email: 'exemple@gmail.com',
    image: 'assets/images/users/avatar-1.jpg',
    id: '#3625',
    role: 'Administrador',
    last_active: 'Yesterday, 10:15pm',
    status: 'Activo',
  },
  {
    name: 'Mickey',
    email: 'josealbertopersonal@gmail.com',
    image: 'assets/images/users/avatar-2.jpg',
    id: '#9514',
    role: 'SubAgente',
    last_active: 'Today, 02:30pm',
    status: 'Activo',
  },
  {
    name: 'Francisco Ventura',
    email: 'ingfranciscoventurac@gmail.com',
    image: 'assets/images/users/avatar-1.jpg',
    id: '#9958',
    role: 'Administrador',
    last_active: 'Today, 02:30pm',
    status: 'Activo',
  },
  {
    name: 'Ben',
    email: 'exemple@gmail.com',
    image: 'assets/images/users/avatar-1.jpg',
    id: '#3625',
    role: 'Administrador',
    last_active: 'Yesterday, 10:15pm',
    status: 'Activo',
  },
  {
    name: 'Mickey',
    email: 'josealbertopersonal@gmail.com',
    image: 'assets/images/users/avatar-2.jpg',
    id: '#9514',
    role: 'SubAgente',
    last_active: 'Today, 02:30pm',
    status: 'Activo',
  },
  {
    name: 'Francisco Ventura',
    email: 'ingfranciscoventurac@gmail.com',
    image: 'assets/images/users/avatar-1.jpg',
    id: '#9958',
    role: 'Administrador',
    last_active: 'Today, 02:30pm',
    status: 'Activo',
  },
  {
    name: 'Ben',
    email: 'exemple@gmail.com',
    image: 'assets/images/users/avatar-1.jpg',
    id: '#3625',
    role: 'Administrador',
    last_active: 'Yesterday, 10:15pm',
    status: 'Activo',
  },
  {
    name: 'Mickey',
    email: 'josealbertopersonal@gmail.com',
    image: 'assets/images/users/avatar-2.jpg',
    id: '#9514',
    role: 'SubAgente',
    last_active: 'Today, 02:30pm',
    status: 'Activo',
  },
  // {
  //   name: 'Steven Sharp',
  //   email: 'dummy@gmail.com',
  //   image: 'assets/images/users/avatar-3.jpg',
  //   id: '#9958',
  //   role: 'Agente',
  //   last_active: 'Today, 02:30pm',
  //   status: 'Inactivo',
  // },
  // {
  //   name: 'Teresa Himes',
  //   email: 'dummy@gmail.com',
  //   image: 'assets/images/users/avatar-4.jpg',
  //   id: '#4545',
  //   role: 'SubAgente',
  //   last_active: '2 mar' + currentYear + ',07:30pm',
  //   status: 'Activo',
  // },
  // {
  //   name: 'Ralph Denton',
  //   email: 'dummy@gmail.com',
  //   image: 'assets/images/users/avatar-5.jpg',
  //   id: '#6325',
  //   role: 'SubAgente',
  //   last_active: 'Today, 02:30pm',
  //   status: 'Inactivo',
  // },
  // {
  //   name: 'Unity Pugh',
  //   email: 'dummy@gmail.com',
  //   image: 'assets/images/users/avatar-1.jpg',
  //   id: '#9958',
  //   role: 'SubAgente',
  //   last_active: 'Today, 02:30pm',
  //   status: 'Activo',
  // },
  // {
  //   name: 'Scott Holland',
  //   email: 'exemple@gmail.com',
  //   image: 'assets/images/users/avatar-1.jpg',
  //   id: '#3625',
  //   role: 'Agente',
  //   last_active: 'Yesterday, 10:15pm',
  //   status: 'Activo',
  // },
  // {
  //   name: 'Karen Savage',
  //   email: 'extradummy@gmail.com',
  //   image: 'assets/images/users/avatar-2.jpg',
  //   id: '#9514',
  //   role: 'SubAgente',
  //   last_active: 'Today, 02:30pm',
  //   status: 'Activo',
  // },
  // {
  //   name: 'Steven Sharp',
  //   email: 'dummy@gmail.com',
  //   image: 'assets/images/users/avatar-3.jpg',
  //   id: '#9958',
  //   role: 'Agente',
  //   last_active: 'Today, 02:30pm',
  //   status: 'Inactivo',
  // },
  // {
  //   name: 'Teresa Himes',
  //   email: 'dummy@gmail.com',
  //   image: 'assets/images/users/avatar-4.jpg',
  //   id: '#4545',
  //   role: 'Sub.SubAgenteistrador',
  //   last_active: '2 mar ' + currentYear + ', 07:30pm',
  //   status: 'Activo',
  // },
  // {
  //   name: 'Ralph Denton',
  //   email: 'dummy@gmail.com',
  //   image: 'assets/images/users/avatar-5.jpg',
  //   id: '#6325',
  //   role: 'SubAgente',
  //   last_active: 'Today, 02:30pm',
  //   status: 'Inactivo',
  // },
  // {
  //   name: 'Karen Savage',
  //   email: 'extradummy@gmail.com',
  //   image: 'assets/images/users/avatar-2.jpg',
  //   id: '#9514',
  //   role: 'SubAgente',
  //   last_active: 'Today, 02:30pm',
  //   status: 'Activo',
  // },
]
